name: CI/CD for Churn Prediction

on:
  push:
    branches:
      - main
    paths:
      - train.py

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awsebcli --upgrade --user
        export PATH=$PATH:$HOME/.local/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build Docker Image
      run: |
        docker build -t churn-app .

    - name: Validate the model in Docker
      run: |
        docker run churn-app python validate.py
      
    - name: Run Tests in Docker
      run: |
        docker run churn-app pytest -v

    - name: Initialize Elastic Beanstalk Application
      run: |
        eb init -p docker churn-app --region eu-west-1

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy churn-env
